export default {
  breakpoints: ['576px', '768px', '992px', '1200px'],
  space: [
    0,
    '0.4rem',
    '0.8rem',
    '1.6rem',
    '3.2rem',
    '6.4rem',
    '12.8rem',
    '25.6rem',
    '51.2rem',
  ],
  fonts: {
    body:
      'Nunito, -apple-system, BlinkMacSystemFont, Helvetica Neue, Helvetica, Arial, sans-serif',
    heading: 'Lora, serif',
    monospace: '"Source Code Pro", monospace',
  },
  fontSizes: [
    0,
    '1.2rem',
    '1.4rem',
    '1.6rem',
    '1.8rem',
    '2rem',
    '2.4rem',
    '3.2rem',
    '4.8rem',
    '6.4rem',
    '9.6rem',
  ],
  sizes: { container: '78rem' },
  layout: { article: { maxWidth: '78rem' } },
  fontWeights: {
    body: 400,
    heading: 600,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.25,
  },
  text: {
    small: {
      fontSize: 1,
    },
    timestamp: {
      fontSize: 2,
      color: '#717171',
    },
    heading: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [6, 6, 7],
    },
    body: {
      fontSize: 4,
    },
    emphasis: {
      fontSize: [5, 6],
      mb: 3,
    },
    medium: {
      fontSize: 6,
      fontWeight: 'heading',
    },
  },
  links: {
    nav: {
      fontSize: [3, 4],
      fontWeight: 'heading',
      verticalAlign: 'middle',
      cursor: 'pointer',
    },
    tag: {
      textDecoration: 'none',
      fontSize: 1,
      padding: 1,
      px: 2,
      borderRadius: '1.2rem',
    },
  },
  useColorSchemeMediaQuery: true,
  colors: {
    text: '#17252a',
    background: '#feffff',
    highlightBg: 'rgb(251, 251, 251)',
    primary: '#2b7a78',
    secondary: '#d83f87',
    highlight: '#3aafa9',
    muted: '#def2f1',
    grey: '#717171',
    modes: {
      dark: {
        text: '#fff',
        background: '#011',
        highlightBg: 'rgb(1, 22, 39)',
        primary: '#0fc',
        secondary: '#f0c',
        highlight: '#0cf',
        muted: '#1B1F3B',
        grey: '#eee',
      },
    },
  },
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
    },
    h1: {
      color: 'text',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [6, 6, 7],
    },
    h2: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [5, 6],
    },
    h3: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 5,
    },
    h4: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 4,
    },
    h5: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 2,
    },
    h6: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 1,
    },
    p: {
      color: 'text',
      fontSize: 4,
      fontFamily: 'body',
      fontWeight: 'body',
      lineHeight: 'body',
      code: {
        fontFamily: 'monospace',
        backgroundColor: 'muted',
        p: 1,
        fontSize: 3,
        borderRadius: '6px',
      },
    },
    a: {
      cursor: 'pointer',
      color: 'primary',
      fontWeight: 'heading',
      textDecoration: 'none',
      position: 'relative',
      transition: 'color .4s ease-out',
      '&:after': {
        position: 'absolute',
        right: '100%',
        left: 0,
        bottom: 0,
        borderRadius: '1rem',
        borderTop: t => `0.2rem solid ${t.colors.secondary}`,
        content: '""',
        transition:
          'right .4s cubic-bezier(0, .5, 0, 1), border-color .4s ease-out',
      },
      '&:hover': {
        color: 'secondary',
        '&:after': {
          right: 0,
          borderColor: 'secondary',
        },
      },
    },
    pre: {
      fontFamily: 'monospace',
      overflowX: 'auto',
      code: {
        color: 'inherit',
      },
    },
    table: {
      width: '100%',
      borderCollapse: 'separate',
      borderSpacing: 0,
    },
    th: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    td: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    img: {
      maxWidth: '100%',
    },
    blockquote: {
      borderLeft: t => `4px solid ${t.colors.primary}`,
      paddingLeft: 3,
      marginRight: 0,
      marginBlockStart: 0,
      marginBlockEnd: 0,
      marginInlineStart: 0,
      marginInlineEnd: 0,
      // width: ['100%', '100%', '140%'],
      // marginLeft: [0, 0, '50%'],
      // transform: [null, null, 'translateX(-50%)'],
      // my: [3, 4],
      p: {
        fontFamily: 'heading',
        fontStyle: 'italic',
        fontSize: 5,
        // lineHeight: ['3rem', '3.5rem'],
        fontWeight: 500,
      },
    },
    ul: {
      m: 0,
      li: { fontSize: 4, mb: 2 },
      mb: 3,
    },
    ol: {
      m: 0,
      li: { fontSize: 4, mb: 2 },
      mb: 3,
    },
    navlink: {
      fontSize: [4, 5],
      textDecoration: 'none',
      color: 'inherit',
      fontWeight: 'heading',
      position: 'relative',
      overflow: 'hidden',
      '&:after': {
        position: 'absolute',
        right: '100%',
        borderRadius: '1rem',
        borderTop: t => `0.3rem solid ${t.colors.grey}`,
        bottom: 0,
        left: 0,
        content: '""',
        transition:
          'right .4s cubic-bezier(0, .5, 0, 1), border-color .4s ease-out',
      },
      '&:hover': {
        color: 'inherit',
        '&:after': {
          borderColor: 'grey',
          right: 0,
        },
      },
      '&.active': {
        color: 'secondary',
        '&:after': {
          borderColor: 'secondary',
          right: 0,
        },
      },
    },
  },
};
